add put post delete document in views.py
MaxCunningham19/legal_spellcheck pull request #82
Opened 2023-03-01 15:14 UTC by QimingNie

add put post delete document in views.py and urls.py

2023-03-01 16:43 UTC, ni-sauvage requested changes
Work looks good, nicely done! I'm just going to request that you add tests to the tests.py file as a sanity check.

2023-03-03 10:46 UTC, QimingNie commented
> 工作看起来不错，做得很好！我只是要求您将测试添加到 tests.py 文件中作为健全性检查。

I'm trying to test it.

2023-03-03 12:54 UTC, MaxCunningham19 requested changes

2023-03-03 12:54 UTC, MaxCunningham19 commented on urls.py
> +    path('document/<int:pk>', delete_document_blocks, name='delete_document_blocks'),
any chance you could change the 'document/' url to 'documents/' in line with the [REST conventions](https://restfulapi.net/resource-naming/)

2023-03-09 20:19 UTC, MaxCunningham19 approved these changes
lgtm

2023-03-09 23:02 UTC, ni-sauvage commented
Superseded by [#90](https://github.com/MaxCunningham19/legal_spellcheck/pull/90). Closing PR.

2023-03-09 23:02 UTC, closed without merging