Ignatii/develop api
MaxCunningham19/legal_spellcheck pull request #85
Opened 2023-03-02 16:12 UTC by IgnAhT

Created 'add_document' view with a corresponding test block. URL path is hooked up to 'add/'.

2023-03-02 16:23 UTC, ni-sauvage approved these changes
I'm happy to merge this, test-cases and functionality look good!

2023-03-03 12:52 UTC, MaxCunningham19 requested changes

2023-03-03 12:52 UTC, MaxCunningham19 commented on api/models.py
> +    block_order = models.IntegerField(default=0)
Q: Should this not still have unique = True?

2023-03-03 12:52 UTC, MaxCunningham19 commented on api/urls.py
> +    path('add/', add_documents, name='add_documents')]
This should just be documents/ according to the [rest convention](https://restfulapi.net/resource-naming/)

2023-03-03 12:52 UTC, MaxCunningham19 commented on api/views.py
> +    return Response(serializer.data, status=200)
I think there should be a check if the serialised is correct incase the document requested doesn't exist

2023-03-09 20:18 UTC, MaxCunningham19 approved these changes
LGTM

2023-03-09 20:55 UTC, merged